name: CI/CD Deploy to Azure

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  call_build_and_deploy_blazor:
    uses: ./.github/workflows/deploy-sttapp.yml
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    with:
      app_type: blazor
      app_location: src/frontend/blazor
      api_location: ''
      output_location: ''
      skip_app_build: true
    secrets: inherit

  call_build_and_deploy_react:
    uses: ./.github/workflows/deploy-sttapp.yml
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    with:
      app_type: react
      app_location: src/frontend/typescript
      api_location: ''
      output_location: 'dist'
      skip_app_build: false
    secrets: inherit

  call_close_pr_blazor:
    uses: ./.github/workflows/close-pr.yml
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    with:
      app_type: blazor
    secrets: inherit

  call_close_pr_react:
    uses: ./.github/workflows/close-pr.yml
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    with:
      app_type: react
    secrets: inherit
