name: Manual Deploy SWA to Azure

on:
  workflow_dispatch:
    inputs:
      resource_name:
        type: string
        required: true
        description: Resource name on Azure

jobs:
  call_build_and_deploy_blazor:
    uses: ./.github/workflows/deploy-sttapp.yml
    with:
      app_type: blazor
      resource_name: ${{ github.event.inputs.resource_name }}
      app_location: src/frontend/blazor
      api_location: ''
      output_location: ''
      skip_app_build: true
    secrets: inherit

  call_build_and_deploy_react:
    uses: ./.github/workflows/deploy-sttapp.yml
    with:
      app_type: react
      resource_name: ${{ github.event.inputs.resource_name }}
      app_location: src/frontend/typescript
      api_location: ''
      output_location: 'dist'
      skip_app_build: true
    secrets: inherit

  update_gh_secrets:
    name: Update GitHub secrets
    needs:
      - call_build_and_deploy_blazor
      - call_build_and_deploy_react
    runs-on: ubuntu-latest
    steps:
      - name: Login to GH CLI
        shell: bash
        run: |
          gh auth login --with-token <<< ${{ secrets.GH_PAT }}

      - name: Update GitHub secrets
        shell: bash
        run: |
          gh secret set AZURE_RESOURCE_NAME --body ${{ github.event.inputs.resource_name }} --repo ${{ github.repository }}
